# Generated by Django 3.0.8 on 2022-07-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_app', '0002_bug_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='team_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
